# Don't print a new line at the start of the prompt
#add_newline = false

#Prompt
format = """
[┌───────────────────>](bold green)
[│](bold green)$username$directory$rust$package$time$cmd_duration$git_branch$git_commit$git_state$git_status
[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
[time]
disabled = false
[username]
disabled = false
show_always = true
